#!/usr/bin/env python3
"""
Aseba Code Exporter for Thymio Robot
Exports PyGameMaker Thymio projects to Aseba AESL format
"""

import json
from pathlib import Path
from typing import Dict, List, Set, Any
from datetime import datetime


class AsebaExporter:
    """Export PyGameMaker Thymio projects to Aseba AESL code"""

    def __init__(self):
        self.variables = set()  # Track all variables used
        self.timer_periods = {}  # Track timer periods {timer_id: period}
        self.indent_level = 0
        self.current_object = None

    def export(self, project_path: str, output_path: str = None) -> bool:
        """
        Export project to Aseba AESL format

        Args:
            project_path: Path to PyGameMaker project.json
            output_path: Output directory for .aesl files (default: same as project)

        Returns:
            True if export successful
        """
        # Load project
        project_path = Path(project_path)
        if not project_path.exists():
            print(f"❌ Project not found: {project_path}")
            return False

        with open(project_path, 'r') as f:
            project_data = json.load(f)

        # Determine output directory
        if output_path is None:
            output_path = project_path.parent / "aseba_export"
        else:
            output_path = Path(output_path)

        output_path.mkdir(exist_ok=True)

        print(f"📦 Exporting Thymio project to Aseba...")
        print(f"   Source: {project_path}")
        print(f"   Output: {output_path}")

        # Find all Thymio objects
        thymio_objects = self._find_thymio_objects(project_data)

        if not thymio_objects:
            print("⚠️  No Thymio objects found in project")
            return False

        print(f"   Found {len(thymio_objects)} Thymio object(s)")

        # Export each Thymio object to separate .aesl file
        success_count = 0
        for obj_name, obj_data in thymio_objects.items():
            print(f"\n🤖 Exporting {obj_name}...")

            # Reset state for this object
            self.variables = set()
            self.timer_periods = {}
            self.current_object = obj_name

            # Generate AESL code
            aesl_code = self.generate_aesl(obj_name, obj_data, project_data)

            # Write to file
            output_file = output_path / f"{obj_name}.aesl"
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(aesl_code)

            print(f"   ✅ Exported to: {output_file}")
            success_count += 1

        # Generate README
        readme_path = output_path / "README.md"
        self._generate_readme(readme_path, project_data, thymio_objects)

        print(f"\n✅ Export complete! {success_count}/{len(thymio_objects)} object(s) exported")
        print(f"📄 See {readme_path} for instructions")

        return True

    def _find_thymio_objects(self, project_data: Dict) -> Dict[str, Dict]:
        """Find all Thymio robot objects in project"""
        thymio_objects = {}

        objects = project_data.get('assets', {}).get('objects', {})

        for obj_name, obj_data in objects.items():
            # Check if it's a Thymio object
            if obj_name.lower().startswith('thymio') or obj_data.get('is_thymio', False):
                thymio_objects[obj_name] = obj_data

        return thymio_objects

    def generate_aesl(self, obj_name: str, obj_data: Dict, project_data: Dict) -> str:
        """Generate complete AESL code for a Thymio object"""
        lines = []

        # Header
        lines.append(self._generate_header(obj_name, project_data))
        lines.append("")

        # Variable declarations
        var_section = self._generate_variables(obj_data)
        if var_section:
            lines.append(var_section)
            lines.append("")

        # Initialization code (from create event)
        init_section = self._generate_initialization(obj_data)
        if init_section:
            lines.append(init_section)
            lines.append("")

        # Subroutines (if any - currently not used)
        # lines.append(self._generate_subroutines(obj_data))

        # Event handlers
        event_section = self._generate_event_handlers(obj_data)
        if event_section:
            lines.append(event_section)

        return '\n'.join(lines)

    def _generate_header(self, obj_name: str, project_data: Dict) -> str:
        """Generate file header comment"""
        project_name = project_data.get('name', 'Untitled')
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')

        return f"""# Aseba code for {obj_name}
# Generated by PyGameMaker
# Project: {project_name}
# Generated: {timestamp}
#
# Upload this code to your Thymio robot using Aseba Studio:
# 1. Connect your Thymio robot via USB
# 2. Open this file in Aseba Studio
# 3. Click "Load" to upload to Thymio
# 4. Click "Run" to start the program"""

    def _generate_variables(self, obj_data: Dict) -> str:
        """Generate variable declarations"""
        # Scan all events to find variables used
        events = obj_data.get('events', {})
        self._scan_for_variables(events)

        if not self.variables:
            return ""

        lines = ["# Variable declarations"]

        for var in sorted(self.variables):
            lines.append(f"var {var}")

        return '\n'.join(lines)

    def _scan_for_variables(self, events: Dict):
        """Scan events to find all variables used"""
        for event_name, event_data in events.items():
            if isinstance(event_data, dict) and 'actions' in event_data:
                self._scan_actions_for_variables(event_data['actions'])

    def _scan_actions_for_variables(self, actions: List[Dict]):
        """Scan actions to find variable declarations and uses"""
        for action in actions:
            action_type = action.get('action', '')
            params = action.get('parameters', {})

            # Variable actions
            if action_type in ['thymio_set_variable', 'thymio_increase_variable',
                              'thymio_decrease_variable', 'thymio_if_variable']:
                var_name = params.get('variable', '')
                if var_name:
                    self.variables.add(var_name)

            # Sensor read actions store in variables
            elif action_type in ['thymio_read_proximity', 'thymio_read_ground', 'thymio_read_button']:
                var_name = params.get('variable', '')
                if var_name:
                    self.variables.add(var_name)

    def _generate_initialization(self, obj_data: Dict) -> str:
        """Generate initialization code from create event"""
        events = obj_data.get('events', {})

        if 'create' not in events:
            return ""

        create_event = events['create']
        actions = create_event.get('actions', [])

        if not actions:
            return ""

        lines = ["# Initialization (runs once on start)"]

        for action in actions:
            code = self._translate_action(action)
            if code:
                lines.append(code)

        return '\n'.join(lines)

    def _generate_event_handlers(self, obj_data: Dict) -> str:
        """Generate all onevent handlers"""
        from events.thymio_events import THYMIO_EVENT_TO_ASEBA

        events = obj_data.get('events', {})
        lines = []

        # Map PyGameMaker events to Aseba events
        event_handlers = {}

        for event_name, event_data in events.items():
            # Skip create event (already handled in initialization)
            if event_name == 'create':
                continue

            # Get Aseba event name
            aseba_event = THYMIO_EVENT_TO_ASEBA.get(event_name, '')
            if not aseba_event:
                continue

            # Store actions for this event
            if aseba_event not in event_handlers:
                event_handlers[aseba_event] = []

            actions = event_data.get('actions', [])
            event_handlers[aseba_event].extend(actions)

        # Generate onevent blocks
        for aseba_event, actions in sorted(event_handlers.items()):
            lines.append(self._generate_event_handler(aseba_event, actions))
            lines.append("")

        return '\n'.join(lines)

    def _generate_event_handler(self, aseba_event: str, actions: List[Dict]) -> str:
        """Generate a single onevent handler"""
        lines = [f"# Event: {aseba_event}"]
        lines.append(aseba_event)

        self.indent_level = 1

        for action in actions:
            code = self._translate_action(action)
            if code:
                lines.append(code)

        lines.append("end")

        self.indent_level = 0

        return '\n'.join(lines)

    def _translate_action(self, action: Dict) -> str:
        """Translate a single action to Aseba code"""
        action_type = action.get('action', '')
        params = action.get('parameters', {})

        # Get translator function
        translator = self._get_action_translator(action_type)

        if translator:
            code = translator(params)
            if code:
                # Add indentation
                indent = '\t' * self.indent_level
                # Handle multi-line code
                if '\n' in code:
                    lines = code.split('\n')
                    return '\n'.join([indent + line if line else '' for line in lines])
                else:
                    return indent + code

        return ""

    def _get_action_translator(self, action_type: str):
        """Get translator function for action type"""
        translators = {
            # Motor actions
            'thymio_set_motor_speed': self._translate_set_motor_speed,
            'thymio_move_forward': self._translate_move_forward,
            'thymio_move_backward': self._translate_move_backward,
            'thymio_turn_left': self._translate_turn_left,
            'thymio_turn_right': self._translate_turn_right,
            'thymio_stop_motors': self._translate_stop_motors,

            # LED actions
            'thymio_set_led_top': self._translate_set_led_top,
            'thymio_set_led_bottom_left': self._translate_set_led_bottom_left,
            'thymio_set_led_bottom_right': self._translate_set_led_bottom_right,
            'thymio_set_led_circle': self._translate_set_led_circle,
            'thymio_set_led_circle_all': self._translate_set_led_circle_all,
            'thymio_leds_off': self._translate_leds_off,

            # Sound actions
            'thymio_play_tone': self._translate_play_tone,
            'thymio_play_system_sound': self._translate_play_system_sound,
            'thymio_stop_sound': self._translate_stop_sound,

            # Sensor conditions
            'thymio_if_proximity': self._translate_if_proximity,
            'thymio_if_ground_dark': self._translate_if_ground_dark,
            'thymio_if_ground_light': self._translate_if_ground_light,
            'thymio_if_button_pressed': self._translate_if_button_pressed,
            'thymio_if_button_released': self._translate_if_button_released,

            # Timer actions
            'thymio_set_timer_period': self._translate_set_timer_period,

            # Variable actions
            'thymio_set_variable': self._translate_set_variable,
            'thymio_increase_variable': self._translate_increase_variable,
            'thymio_decrease_variable': self._translate_decrease_variable,
            'thymio_if_variable': self._translate_if_variable,

            # Control flow
            'start_block': self._translate_start_block,
            'end_block': self._translate_end_block,
            'else': self._translate_else,
            'else_action': self._translate_else,
            'else_block': self._translate_else,
        }

        return translators.get(action_type)

    # ========================================================================
    # ACTION TRANSLATORS
    # ========================================================================

    def _translate_set_motor_speed(self, params: Dict) -> str:
        left = params.get('left_speed', '0')
        right = params.get('right_speed', '0')
        return f"motor.left.target = {left}\nmotor.right.target = {right}"

    def _translate_move_forward(self, params: Dict) -> str:
        speed = params.get('speed', '200')
        return f"motor.left.target = {speed}\nmotor.right.target = {speed}"

    def _translate_move_backward(self, params: Dict) -> str:
        speed = params.get('speed', '200')
        return f"motor.left.target = -{speed}\nmotor.right.target = -{speed}"

    def _translate_turn_left(self, params: Dict) -> str:
        speed = params.get('speed', '300')
        return f"motor.left.target = 0\nmotor.right.target = {speed}"

    def _translate_turn_right(self, params: Dict) -> str:
        speed = params.get('speed', '300')
        return f"motor.left.target = {speed}\nmotor.right.target = 0"

    def _translate_stop_motors(self, params: Dict) -> str:
        return "motor.left.target = 0\nmotor.right.target = 0"

    def _translate_set_led_top(self, params: Dict) -> str:
        r = params.get('red', '0')
        g = params.get('green', '0')
        b = params.get('blue', '0')
        return f"call leds.top({r}, {g}, {b})"

    def _translate_set_led_bottom_left(self, params: Dict) -> str:
        r = params.get('red', '0')
        g = params.get('green', '0')
        b = params.get('blue', '0')
        return f"call leds.bottom.left({r}, {g}, {b})"

    def _translate_set_led_bottom_right(self, params: Dict) -> str:
        r = params.get('red', '0')
        g = params.get('green', '0')
        b = params.get('blue', '0')
        return f"call leds.bottom.right({r}, {g}, {b})"

    def _translate_set_led_circle(self, params: Dict) -> str:
        # Note: Aseba sets all circle LEDs at once, so this is approximate
        return "# Note: Individual circle LED control not directly supported"

    def _translate_set_led_circle_all(self, params: Dict) -> str:
        values = []
        for i in range(8):
            val = params.get(f'led{i}', '0')
            values.append(str(val))
        return f"call leds.circle({', '.join(values)})"

    def _translate_leds_off(self, params: Dict) -> str:
        return "call leds.top(0, 0, 0)\ncall leds.circle(0, 0, 0, 0, 0, 0, 0, 0)"

    def _translate_play_tone(self, params: Dict) -> str:
        freq = params.get('frequency', '440')
        duration = params.get('duration', '60')
        return f"call sound.freq({freq}, {duration})"

    def _translate_play_system_sound(self, params: Dict) -> str:
        sound_id = params.get('sound_id', '0')
        # Parse sound_id if it's a string like "0 - Startup"
        if isinstance(sound_id, str) and ' - ' in sound_id:
            sound_id = sound_id.split(' - ')[0].strip()
        return f"call sound.system({sound_id})"

    def _translate_stop_sound(self, params: Dict) -> str:
        return "call sound.freq(0, -1)"

    def _translate_if_proximity(self, params: Dict) -> str:
        sensor = params.get('sensor_index', '2')
        threshold = params.get('threshold', '2000')
        comparison = params.get('comparison', '>')
        self.indent_level += 1
        return f"if prox.horizontal[{sensor}] {comparison} {threshold} then"

    def _translate_if_ground_dark(self, params: Dict) -> str:
        sensor = params.get('sensor_index', '0')
        threshold = params.get('threshold', '300')
        self.indent_level += 1
        return f"if prox.ground.delta[{sensor}] < {threshold} then"

    def _translate_if_ground_light(self, params: Dict) -> str:
        sensor = params.get('sensor_index', '0')
        threshold = params.get('threshold', '300')
        self.indent_level += 1
        return f"if prox.ground.delta[{sensor}] >= {threshold} then"

    def _translate_if_button_pressed(self, params: Dict) -> str:
        button = params.get('button', 'center')
        self.indent_level += 1
        return f"if button.{button} == 1 then"

    def _translate_if_button_released(self, params: Dict) -> str:
        button = params.get('button', 'center')
        self.indent_level += 1
        return f"if button.{button} == 0 then"

    def _translate_set_timer_period(self, params: Dict) -> str:
        timer_id = params.get('timer_id', '0')
        period = params.get('period', '1000')
        self.timer_periods[timer_id] = period
        return f"timer.period[{timer_id}] = {period}"

    def _translate_set_variable(self, params: Dict) -> str:
        var = params.get('variable', 'state')
        value = params.get('value', '0')
        return f"{var} = {value}"

    def _translate_increase_variable(self, params: Dict) -> str:
        var = params.get('variable', 'counter')
        amount = params.get('amount', '1')
        if amount == '1':
            return f"{var}++"
        else:
            return f"{var} = {var} + {amount}"

    def _translate_decrease_variable(self, params: Dict) -> str:
        var = params.get('variable', 'counter')
        amount = params.get('amount', '1')
        if amount == '1':
            return f"{var}--"
        else:
            return f"{var} = {var} - {amount}"

    def _translate_if_variable(self, params: Dict) -> str:
        var = params.get('variable', 'state')
        comparison = params.get('comparison', '==')
        value = params.get('value', '0')
        self.indent_level += 1
        return f"if {var} {comparison} {value} then"

    def _translate_start_block(self, params: Dict) -> str:
        # Block start is implicit after 'then' in Aseba
        return ""

    def _translate_end_block(self, params: Dict) -> str:
        self.indent_level -= 1
        return "end"

    def _translate_else(self, params: Dict) -> str:
        self.indent_level -= 1
        result = "else"
        self.indent_level += 1
        return result

    def _generate_readme(self, readme_path: Path, project_data: Dict, thymio_objects: Dict):
        """Generate README with usage instructions"""
        project_name = project_data.get('name', 'Untitled')

        content = f"""# Aseba Export - {project_name}

Generated by PyGameMaker on {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Files

"""
        for obj_name in thymio_objects.keys():
            content += f"- `{obj_name}.aesl` - Aseba code for {obj_name}\n"

        content += """
## How to Upload to Thymio

1. **Connect your Thymio robot:**
   - Connect Thymio to your computer via USB cable
   - Turn on the Thymio robot

2. **Open Aseba Studio:**
   - Launch Aseba Studio software
   - It should automatically detect your Thymio

3. **Load the code:**
   - In Aseba Studio, click File → Open
   - Select the `.aesl` file for your robot
   - The code will appear in the editor

4. **Upload to Thymio:**
   - Click the "Load" button to upload code to Thymio
   - Click the "Run" button to start the program

5. **Test your robot:**
   - Use Thymio's buttons to control it
   - Observe LED feedback and behavior

## Notes

- The exported code uses Aseba's event-driven model
- All PyGameMaker events are translated to `onevent` handlers
- Variables are declared at the top of the file
- Timer periods are set in initialization

## Troubleshooting

**Robot not detected:**
- Check USB cable connection
- Try a different USB port
- Restart Aseba Studio

**Code doesn't upload:**
- Check for syntax errors in Aseba Studio
- Verify all variables are declared
- Check that event names are correct

**Robot behavior different from simulation:**
- Real sensors may behave differently than simulated
- Adjust threshold values as needed
- Test in similar environment to simulation

## Resources

- [Thymio Official Website](https://www.thymio.org/)
- [Aseba Documentation](https://mobsya.github.io/aseba/)
- [Thymio Programming Guide](https://www.thymio.org/products/programming-with-thymio-suite/)
"""

        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(content)


# ============================================================================
# COMMAND LINE INTERFACE
# ============================================================================

def main():
    """Command line interface for Aseba exporter"""
    import sys

    if len(sys.argv) < 2:
        print("Usage: python aseba_exporter.py <project.json> [output_dir]")
        print("\nExample:")
        print("  python aseba_exporter.py my_project/project.json")
        print("  python aseba_exporter.py my_project/project.json export/")
        return

    project_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else None

    exporter = AsebaExporter()
    success = exporter.export(project_path, output_path)

    if success:
        print("\n✅ Export successful!")
        sys.exit(0)
    else:
        print("\n❌ Export failed")
        sys.exit(1)


if __name__ == '__main__':
    main()
