#!/usr/bin/env python3
"""Slice each tutorial's "Worksheet Answer Key" out of its teacher guide into
a standalone, printable Answer Key page.

Source of truth stays docs/handouts/<NN_slug>/teacher.<lang>.md -- a teacher
guide already carries a "## Worksheet Answer Key" ("## Corrigé de la feuille
d'exercices") section written to match its worksheet's question numbers.
This script only extracts that section (up to the next "## " heading) and
wraps it with a title (the worksheet's own title, suffix swapped) and a
teachers-only notice, so a teacher can print/hand around just the answers
without carrying the whole teacher guide (timing table, rubric, etc).

docs/handouts/<NN_slug>/answer_key.<lang>.md is GENERATED by this script --
do not hand-edit it. Edit the "Worksheet Answer Key" section of
teacher.<lang>.md instead and re-run this script (scripts/build_teacher_wiki.py
also calls it automatically before building the wiki pages, so a plain
`python scripts/build_teacher_wiki.py` keeps it current too).

Usage:  python scripts/extract_worksheet_answer_keys.py
"""
import glob
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "docs", "handouts")

HEADING = {"en": "## Worksheet Answer Key", "fr": "## Corrigé de la feuille d'exercices"}
NOTICE = {
    "en": "> INFO: For teachers only -- do not hand out to students. The "
          "numbering below matches this tutorial's Worksheet.",
    "fr": "> INFO: Réservé aux enseignant·e·s -- ne pas distribuer aux "
          "élèves. La numérotation ci-dessous correspond à la Feuille "
          "d'exercices de ce tutoriel.",
}
GENERATED_COMMENT = (
    "<!-- GENERATED by scripts/extract_worksheet_answer_keys.py from this "
    "tutorial's teacher.{lang}.md -- do not hand-edit; edit the \"{heading}\" "
    "section there instead and re-run the script. -->"
)


def extract_section(teacher_md, lang):
    """Return the Worksheet Answer Key section (heading + body), or None if
    the teacher guide has no such section."""
    lines = teacher_md.splitlines()
    heading = HEADING[lang]
    if heading not in lines:
        return None
    start = lines.index(heading)
    end = start + 1
    while end < len(lines) and not lines[end].startswith("## "):
        end += 1
    body = lines[start:end]
    while body and not body[-1].strip():
        body.pop()
    return "\n".join(body) + "\n"


def worksheet_title(worksheet_md):
    for ln in worksheet_md.splitlines():
        if ln.startswith("# "):
            return ln[2:].strip()
    return None


def answer_key_title(title, lang):
    if lang == "en":
        return re.sub(r"Worksheet$", "Answer Key", title)
    return re.sub(r"Feuille d'exercices$", "Corrigé", title)


def build_answer_key_md(nn_dir, lang):
    """Return the generated answer_key.<lang>.md text for one tutorial dir,
    or None if that tutorial has no worksheet/teacher guide (yet) in `lang`."""
    teacher_path = os.path.join(nn_dir, f"teacher.{lang}.md")
    worksheet_path = os.path.join(nn_dir, f"worksheet.{lang}.md")
    if not (os.path.isfile(teacher_path) and os.path.isfile(worksheet_path)):
        return None
    teacher_md = open(teacher_path, encoding="utf-8").read()
    section = extract_section(teacher_md, lang)
    if section is None:
        return None
    title = worksheet_title(open(worksheet_path, encoding="utf-8").read())
    return (
        f"# {answer_key_title(title, lang)}\n\n"
        f"{GENERATED_COMMENT.format(lang=lang, heading=HEADING[lang])}\n\n"
        f"{NOTICE[lang]}\n\n"
        f"{section}"
    )


def build(write=True):
    written = []
    for d in sorted(glob.glob(os.path.join(SRC, "[0-9][0-9]_*"))):
        for lang in ("en", "fr"):
            md = build_answer_key_md(d, lang)
            if md is None:
                continue
            out = os.path.join(d, f"answer_key.{lang}.md")
            if write:
                with open(out, "w", encoding="utf-8", newline="\n") as fh:
                    fh.write(md)
            written.append(out)
    return written


if __name__ == "__main__":
    made = build()
    print(f"wrote {len(made)} answer_key.<lang>.md file(s)")
