// export_html5.js -- the Block World voxel renderer's HTML5 port (Phase 6
// Unit 8 of docs/VOXEL_WORLD_PLAN.md). Concatenated at engine.js's
// __PYGM_EXTENSION_JS__ marker (Stage-C pattern established by
// extensions/raycast_2_5d/export_html5.js -- see that file's own header for
// the mechanism). engine.js itself names nothing here.
//
// Mirrors extensions/block_world/state.py + renderer.py + handlers.py +
// hud.py, with ONE deliberate, documented scope reduction: walls and top/
// bottom faces are FLAT-COLORED using each block type's precomputed average
// texture color (BLOCK_FACE_COLORS below, generated by
// tools/gen_block_world_face_colors.py from the real bundled PNGs), not real
// per-pixel texture mapping. Porting desktop's texture-cropping/sub-texel
// pipeline to a second hand-written renderer was judged not worth it for a
// first export cut -- same category as raycast's still-open per-target
// floor-casting deferral. `top_cast_res` is accepted as a valid
// enable_block_world_view parameter but has no effect here (there is no
// per-pixel path to control the resolution of). The occlusion early-out
// (_fully_covers on desktop) is also skipped: a pure perf shortcut, since
// the far-to-near painter's-algorithm draw order is correct without it.
//
// `load_block_world`'s data file has no filesystem to read from in a
// browser -- see extensions/block_world/export_data.py, whose
// collect_export_data() embeds every referenced file into
// gameData._extension_data.block_world_files at export time.

// Precomputed per-block-type average face colors (see
// tools/generated/block_world_face_colors.json / gen_block_world_face_colors.py
// -- pinned by tests/test_block_world_export_face_colors.py against a live
// recomputation, so this table cannot silently drift from the bundled art).
const BLOCK_FACE_COLORS = {
    brick: { top: [124,78,72], bottom: [124,78,72], side: [124,78,72] },
    clay: { top: [180,162,136], bottom: [180,162,136], side: [180,162,136] },
    coal_block: { top: [55,55,56], bottom: [55,55,56], side: [55,55,56] },
    cobble: { top: [116,127,126], bottom: [116,127,126], side: [116,127,126] },
    desert_sand: { top: [223,213,154], bottom: [223,213,154], side: [223,213,154] },
    diamond_block: { top: [99,143,180], bottom: [99,143,180], side: [99,143,180] },
    dirt: { top: [172,124,68], bottom: [172,124,68], side: [172,124,68] },
    glass: { top: [137,156,168], bottom: [137,156,168], side: [137,156,168] },
    gold_block: { top: [220,145,61], bottom: [220,145,61], side: [220,145,61] },
    grass: { top: [49,141,0], bottom: [172,124,68], side: [46,135,0] },
    gravel: { top: [115,116,112], bottom: [115,116,112], side: [115,116,112] },
    ice: { top: [174,204,225], bottom: [174,204,225], side: [174,204,225] },
    jungle_plank: { top: [102,77,51], bottom: [102,77,51], side: [102,77,51] },
    leaves: { top: [58,136,58], bottom: [58,136,58], side: [58,136,58] },
    mese_block: { top: [152,121,69], bottom: [152,121,69], side: [152,121,69] },
    obsidian: { top: [31,30,30], bottom: [31,30,30], side: [31,30,30] },
    pine_plank: { top: [196,150,93], bottom: [196,150,93], side: [196,150,93] },
    sand: { top: [218,204,171], bottom: [218,204,171], side: [218,204,171] },
    sandstone: { top: [196,173,122], bottom: [196,173,122], side: [196,173,122] },
    snow: { top: [232,231,231], bottom: [232,231,231], side: [232,231,231] },
    stone: { top: [154,154,150], bottom: [154,154,150], side: [154,154,150] },
    water: { top: [92,169,31], bottom: [92,169,31], side: [92,169,31] },
    wood_log: { top: [134,103,78], bottom: [134,103,78], side: [95,62,40] },
    wood_plank: { top: [139,98,50], bottom: [139,98,50], side: [139,98,50] },
    wool_black: { top: [30,30,30], bottom: [30,30,30], side: [30,30,30] },
    wool_blue: { top: [33,29,154], bottom: [33,29,154], side: [33,29,154] },
    wool_green: { top: [50,154,29], bottom: [50,154,29], side: [50,154,29] },
    wool_red: { top: [154,29,29], bottom: [154,29,29], side: [154,29,29] },
    wool_white: { top: [227,227,226], bottom: [227,227,226], side: [227,227,226] },
    wool_yellow: { top: [236,162,0], bottom: [236,162,0], side: [236,162,0] },
};

// The one block type break_block refuses to remove (state.BLOCK_TYPES'
// single 'breakable': False entry).
const BW_UNBREAKABLE = new Set(['obsidian']);

// Mirrors state.DEFAULT_HOTBAR exactly (order matters -- select_hotbar_slot
// indexes into it).
const BW_DEFAULT_HOTBAR = ['cobble', 'brick', 'wood_plank', 'glass',
                            'wool_red', 'sandstone', 'gold_block', 'leaves'];

// Shading constants -- mirror renderer.py's SIDE_SHADE/FOG_STRENGTH/
// MIN_SHADE/TOP_SHADE/BOTTOM_SHADE/DEFAULT_EYE_HEIGHT/MAX_PITCH_DEGREES
// exactly (deliberately duplicated per block, not shared code, matching
// this extension's own state.py precedent of independent removability).
const BW_SIDE_SHADE = 0.85;
const BW_FOG_STRENGTH = 0.55;
const BW_MIN_SHADE = 0.35;
const BW_TOP_SHADE = 1.15;
const BW_BOTTOM_SHADE = 0.55;
const BW_DEFAULT_EYE_HEIGHT = 1.5;
const BW_MAX_PITCH_DEGREES = 70.0;
const BW_DEFAULT_MAX_STEP_UP = 1;

// --- state.py port (free functions taking a GameRoom, mirroring the
// desktop module's own free-function style over `room`) -----------------

function bwKey(x, y, z) { return x + ',' + y + ',' + z; }

function bwGetBlock(room, x, y, z) {
    const blocks = room._bwBlocks;
    if (!blocks) return null;
    const v = blocks[bwKey(x, y, z)];
    return v === undefined ? null : v;
}

function bwSetBlock(room, x, y, z, blockType) {
    if (!room._bwBlocks) room._bwBlocks = {};
    room._bwBlocks[bwKey(x, y, z)] = blockType;
    room._bwColumns = null;
}

function bwRemoveBlock(room, x, y, z) {
    if (!room._bwBlocks) return;
    delete room._bwBlocks[bwKey(x, y, z)];
    room._bwColumns = null;
}

// {(x,y): [[z, blockType], ...]} sorted lowest z first, cached until a
// mutator clears room._bwColumns -- mirrors state.column_index.
function bwColumnIndex(room) {
    if (room._bwColumns) return room._bwColumns;
    const index = {};
    const blocks = room._bwBlocks || {};
    for (const key in blocks) {
        const parts = key.split(',');
        const cx = parts[0], cy = parts[1], z = parseInt(parts[2], 10);
        const ck = cx + ',' + cy;
        if (!index[ck]) index[ck] = [];
        index[ck].push([z, blocks[key]]);
    }
    for (const ck in index) index[ck].sort((a, b) => a[0] - b[0]);
    room._bwColumns = index;
    return index;
}

function bwStackTop(room, x, y) {
    const col = bwColumnIndex(room)[x + ',' + y];
    return (col && col.length) ? col[col.length - 1][0] : null;
}

function bwGroundLayer(room, x, y) {
    const top = bwStackTop(room, x, y);
    return top === null ? 0 : top + 1;
}

function bwCanEnter(room, x, y, standingLayer, maxStepUp) {
    if (maxStepUp === undefined) maxStepUp = BW_DEFAULT_MAX_STEP_UP;
    return bwGroundLayer(room, x, y) - standingLayer <= maxStepUp;
}

function bwCellOf(pixelValue, cellSize) {
    return Math.floor((pixelValue + cellSize / 2) / cellSize);
}

function bwHexToRgb(hex) {
    const h = String(hex || '#888888').replace('#', '');
    if (h.length !== 6) return [136, 136, 136];
    return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}

// --- renderer.py port ----------------------------------------------------

// The DDA: yields one entry per cell ENTERED, mirroring march_ray. No tex_u
// -- this port never texture-maps, so the wall-coordinate math renderer.py
// derives it from is dead weight here.
function* bwMarchRay(px, py, angleRad, cellSize, maxCells) {
    const pxCell = px / cellSize, pyCell = py / cellSize;
    const dx = Math.cos(angleRad), dy = Math.sin(angleRad);
    let mapX = Math.floor(pxCell), mapY = Math.floor(pyCell);
    const deltaX = dx !== 0 ? Math.abs(1 / dx) : 1e30;
    const deltaY = dy !== 0 ? Math.abs(1 / dy) : 1e30;
    let stepX, sideX, stepY, sideY;
    if (dx < 0) { stepX = -1; sideX = (pxCell - mapX) * deltaX; }
    else { stepX = 1; sideX = (mapX + 1 - pxCell) * deltaX; }
    if (dy < 0) { stepY = -1; sideY = (pyCell - mapY) * deltaY; }
    else { stepY = 1; sideY = (mapY + 1 - pyCell) * deltaY; }
    for (let i = 0; i < maxCells; i++) {
        let side, entry;
        if (sideX < sideY) {
            sideX += deltaX; mapX += stepX; side = 0; entry = sideX - deltaX;
        } else {
            sideY += deltaY; mapY += stepY; side = 1; entry = sideY - deltaY;
        }
        const exitCells = sideX < sideY ? sideX : sideY;
        yield {
            mapX, mapY, side,
            entry: Math.max(entry, 1e-4) * cellSize,
            exit: exitCells * cellSize,
        };
    }
}

function bwEyeZFor(cfg) {
    const eyeHeight = cfg.eye_height !== undefined ? cfg.eye_height : BW_DEFAULT_EYE_HEIGHT;
    return Math.trunc(cfg.z_layer || 0) + eyeHeight;
}

function bwClampPitch(pitchDegrees) {
    return Math.max(-BW_MAX_PITCH_DEGREES, Math.min(BW_MAX_PITCH_DEGREES, pitchDegrees));
}

function bwHorizonFor(screenH, pitchDegrees) {
    const pitch = bwClampPitch(pitchDegrees);
    return screenH * 0.5 + screenH * Math.tan(pitch * Math.PI / 180);
}

function bwScreenRay(sx, sy, facingScreenRad, fovRad, screenW, screenH, cellSize, horizon) {
    const cameraX = 2.0 * sx / screenW - 1.0;
    const offset = Math.atan(Math.tan(fovRad / 2) * cameraX);
    if (horizon === undefined) horizon = screenH * 0.5;
    const zPerPx = -(sy - horizon) * Math.cos(offset) / (screenH * cellSize);
    return { angle: facingScreenRad + offset, zPerPx };
}

// Mirrors pick_voxel exactly (see renderer.py's docstring for the gap/
// placement rules); returns {target, placement}, each [x,y,z] or null.
function bwPickVoxel(room, camX, camY, eyeZ, angleRad, zPerPx, cellSize, reach, zMin, zMax) {
    if (zMin === undefined) zMin = -64;
    if (zMax === undefined) zMax = 256;
    let first = null, prev = null, gap = null;
    for (const hit of bwMarchRay(camX, camY, angleRad, cellSize, reach)) {
        const zEntry = eyeZ + zPerPx * hit.entry;
        const zExit = eyeZ + zPerPx * hit.exit;
        const low0 = zEntry <= zExit ? zEntry : zExit;
        const high0 = zEntry <= zExit ? zExit : zEntry;
        const low = Math.max(Math.floor(low0), zMin);
        const high = Math.min(Math.floor(high0), zMax);
        if (high < low) continue;
        const layers = [];
        if (zPerPx >= 0) { for (let l = low; l <= high; l++) layers.push(l); }
        else { for (let l = high; l >= low; l--) layers.push(l); }
        for (const layer of layers) {
            if (first === null) first = [hit.mapX, hit.mapY, layer];
            if (bwGetBlock(room, hit.mapX, hit.mapY, layer) !== null) {
                if (gap !== null) return { target: [hit.mapX, hit.mapY, layer], placement: gap };
                return { target: [hit.mapX, hit.mapY, layer], placement: prev };
            }
            if (gap === null && bwGetBlock(room, hit.mapX, hit.mapY, layer + 1) !== null) {
                gap = [hit.mapX, hit.mapY, layer];
            }
            prev = [hit.mapX, hit.mapY, layer];
        }
    }
    if (gap !== null) return { target: null, placement: gap };
    return { target: null, placement: first };
}

function bwWallShade(side, corrected, maxDist) {
    const sideFactor = side === 1 ? BW_SIDE_SHADE : 1.0;
    let t = maxDist > 0 ? corrected / maxDist : 0.0;
    t = Math.max(0, Math.min(1, t));
    const distFactor = 1.0 - BW_FOG_STRENGTH * t;
    return Math.max(BW_MIN_SHADE, sideFactor * distFactor);
}

function bwFaceShade(corrected, maxDist, facing) {
    let t = maxDist > 0 ? corrected / maxDist : 0.0;
    t = Math.max(0, Math.min(1, t));
    return Math.max(BW_MIN_SHADE, Math.min(1.0, facing * (1.0 - BW_FOG_STRENGTH * t)));
}

function bwShadeColor(rgb, shade) {
    return `rgb(${Math.round(rgb[0] * shade)},${Math.round(rgb[1] * shade)},${Math.round(rgb[2] * shade)})`;
}

// Mirrors _has_neighbor: is there a stack entry at stack[index]'s z + delta?
function bwHasNeighbor(stack, index, delta) {
    const j = index + (delta > 0 ? 1 : -1);
    return j >= 0 && j < stack.length && stack[j][0] === stack[index][0] + delta;
}

// Mirrors render_block_world_view (see that docstring for the full
// projection derivation) minus texture mapping and the _fully_covers
// early-out -- see this file's header comment for why both are scoped out.
function bwRenderView(room, ctx) {
    const cfg = room.blockWorldCamera;
    const cellSize = cfg.cell_size || 32;
    const w = ctx.canvas.width, h = ctx.canvas.height;
    const horizon = bwHorizonFor(h, cfg.pitch || 0.0);

    ctx.fillStyle = cfg.ceiling_color || '#87CEEB';
    ctx.fillRect(0, 0, w, Math.trunc(horizon));
    ctx.fillStyle = cfg.floor_color || '#3a2f1c';
    ctx.fillRect(0, Math.trunc(horizon), w, h - Math.trunc(horizon));

    const camera = room.findFirstInstance(cfg.camera_object || '');
    if (!camera) return;   // flat floor/ceiling only

    // Ray origin is the camera's sprite CENTRE, not its raw x/y -- avoids
    // the exact-grid-line DDA hazard a grid-aligned body at rest would
    // otherwise hit (see renderer.py's identical comment).
    const camTL = GameRoom.spriteTopLeft(camera);
    const camX = camTL.x + camera.boxWidth() / 2;
    const camY = camTL.y + camera.boxHeight() / 2;
    const eyeZ = bwEyeZFor(cfg);

    const wallColorRgb = bwHexToRgb(cfg.wall_color || '#8a8a8a');
    const fovRad = (cfg.fov || 66) * Math.PI / 180;
    const renderDistanceCells = cfg.render_distance || 20;
    const maxDist = renderDistanceCells * cellSize;
    const numColumns = cfg.columns || Math.min(w, 320);
    const colWidth = w / numColumns;
    const facingScreenRad = -camera.facing_angle * Math.PI / 180;
    const planeTan = Math.tan(fovRad / 2);
    const textured = cfg.wall_textured !== false;
    const columns = bwColumnIndex(room);

    for (let col = 0; col < numColumns; col++) {
        const cameraX = 2.0 * (col + 0.5) / numColumns - 1.0;
        const rayOffset = Math.atan(planeTan * cameraX);
        const rayAngle = facingScreenRad + rayOffset;
        const cosOff = Math.cos(rayOffset);   // fisheye correction
        const x0 = Math.floor(col * colWidth), x1 = Math.floor((col + 1) * colWidth);
        const stripW = Math.max(1, x1 - x0);

        // Collect near->far, paint far->near (painter's algorithm).
        const hits = [];
        for (const hit of bwMarchRay(camX, camY, rayAngle, cellSize, renderDistanceCells)) {
            const stack = columns[hit.mapX + ',' + hit.mapY];
            if (!stack || !stack.length) continue;   // air column
            const near = Math.max(hit.entry * cosOff, 1e-4);
            const far = Math.max(hit.exit * cosOff, near);
            const pxPerCell = h * cellSize / near;
            hits.push({ near, far, side: hit.side, stack, pxPerCell });
        }

        for (let hi = hits.length - 1; hi >= 0; hi--) {
            const hitInfo = hits[hi];
            const near = hitInfo.near, far = hitInfo.far, side = hitInfo.side, stack = hitInfo.stack;
            const pxPerCell = hitInfo.pxPerCell;
            const pxPerCellFar = h * cellSize / far;
            const shade = bwWallShade(side, near, maxDist);
            const mid = (near + far) / 2.0;

            for (let i = 0; i < stack.length; i++) {
                const z = stack[i][0], blockType = stack[i][1];
                const colorSet = textured ? BLOCK_FACE_COLORS[blockType] : null;
                const sideColor = colorSet ? colorSet.side : wallColorRgb;

                const yTop = horizon + (eyeZ - (z + 1)) * pxPerCell;
                const y0v = Math.max(0, Math.floor(yTop));
                const y1v = Math.min(h, Math.ceil(yTop + pxPerCell));
                if (y1v > y0v) {
                    ctx.fillStyle = bwShadeColor(sideColor, shade);
                    ctx.fillRect(x0, y0v, stripW, y1v - y0v);
                }

                const above = bwHasNeighbor(stack, i, 1);
                const below = bwHasNeighbor(stack, i, -1);

                if (eyeZ > z + 1 && !above) {
                    const lit = bwFaceShade(mid, maxDist, BW_TOP_SHADE);
                    const yFar = horizon + (eyeZ - (z + 1)) * pxPerCellFar;
                    const yNear = horizon + (eyeZ - (z + 1)) * pxPerCell;
                    const color = colorSet ? colorSet.top : wallColorRgb;
                    const fy0 = Math.max(0, Math.floor(Math.min(yFar, yNear)));
                    const fy1 = Math.min(h, Math.ceil(Math.max(yFar, yNear)));
                    if (fy1 > fy0) {
                        ctx.fillStyle = bwShadeColor(color, lit);
                        ctx.fillRect(x0, fy0, stripW, fy1 - fy0);
                    }
                } else if (eyeZ < z && !below) {
                    const lit = bwFaceShade(mid, maxDist, BW_BOTTOM_SHADE);
                    const yNear = horizon + (eyeZ - z) * pxPerCell;
                    const yFar = horizon + (eyeZ - z) * pxPerCellFar;
                    const color = colorSet ? colorSet.bottom : wallColorRgb;
                    const fy0 = Math.max(0, Math.floor(Math.min(yNear, yFar)));
                    const fy1 = Math.min(h, Math.ceil(Math.max(yNear, yFar)));
                    if (fy1 > fy0) {
                        ctx.fillStyle = bwShadeColor(color, lit);
                        ctx.fillRect(x0, fy0, stripW, fy1 - fy0);
                    }
                }
            }
        }
    }
}

registerRoomRenderer(function(room, ctx) {
    if (room.blockWorldCamera && room.blockWorldCamera.enabled) {
        bwRenderView(room, ctx);
        return true;
    }
    return false;
});

// --- hud.py port -----------------------------------------------------------

function bwBuildHudCommands(screenWidth, screenHeight, hotbar, selectedIndex,
                             slotSize, gap, marginBottom, backColor, borderColor,
                             selectedColor, textColor, crosshairSize, crosshairColor) {
    const cmds = [];
    const ccx = screenWidth / 2.0, ccy = screenHeight / 2.0;
    const half = crosshairSize / 2.0;
    cmds.push({ type: 'line', x1: ccx - half, y1: ccy, x2: ccx + half, y2: ccy, color: crosshairColor });
    cmds.push({ type: 'line', x1: ccx, y1: ccy - half, x2: ccx, y2: ccy + half, color: crosshairColor });

    const n = hotbar.length;
    if (n === 0) return cmds;
    const totalW = n * slotSize + (n - 1) * gap;
    const x0 = (screenWidth - totalW) / 2.0;
    const y0 = screenHeight - marginBottom - slotSize;
    for (let i = 0; i < n; i++) {
        const blockType = hotbar[i];
        const sx = x0 + i * (slotSize + gap);
        const fill = i === selectedIndex ? selectedColor : backColor;
        cmds.push({ type: 'rectangle', x1: sx, y1: y0, x2: sx + slotSize, y2: y0 + slotSize, color: fill, filled: true });
        cmds.push({ type: 'rectangle', x1: sx, y1: y0, x2: sx + slotSize, y2: y0 + slotSize, color: borderColor, filled: false });
        cmds.push({ type: 'text', text: blockType.slice(0, 4), x: sx + 2, y: y0 + slotSize - 14, color: textColor });
    }
    return cmds;
}

// ---------------------------------------------------------------------------
// Block World ACTIONS. Registered into engine.js's action switch via its
// default case (registerExtensionAction), mirroring extensions/raycast_2_5d/
// export_html5.js's own action-registration block. Each handler's (obj,
// params, game) args are the acting instance / action params / the Game.
// ---------------------------------------------------------------------------

function bwPick(obj, params, game) {
    if (!game || !game.currentRoom) return null;
    const room = game.currentRoom;
    const cfg = room.blockWorldCamera;
    if (!cfg || !cfg.enabled) return null;
    const camera = room.findFirstInstance(cfg.camera_object || '');
    if (!camera) return null;

    let reach = Math.trunc(parseNumParam(params.reach, obj, 5));
    reach = Math.max(1, reach);
    const cellSize = cfg.cell_size || 32;
    const camTL = GameRoom.spriteTopLeft(camera);
    const eyeZ = bwEyeZFor(cfg);

    const screenW = (game.canvas && game.canvas.width) || 640;
    const screenH = (game.canvas && game.canvas.height) || 480;
    const fovRad = (cfg.fov || 66) * Math.PI / 180;
    const horizon = bwHorizonFor(screenH, cfg.pitch || 0.0);
    const facingScreenRad = -camera.facing_angle * Math.PI / 180;
    const ray = bwScreenRay(screenW / 2.0, screenH / 2.0, facingScreenRad,
                             fovRad, screenW, screenH, cellSize, horizon);

    const camX = camTL.x + camera.boxWidth() / 2;
    const camY = camTL.y + camera.boxHeight() / 2;
    const picked = bwPickVoxel(room, camX, camY, eyeZ, ray.angle, ray.zPerPx, cellSize, reach);
    return { room, target: picked.target, placement: picked.placement };
}

registerExtensionAction('set_look_pitch', function(obj, params, game) {
    if (!game || !game.currentRoom) return;
    const cfg = game.currentRoom.blockWorldCamera;
    if (!cfg) return;
    let pitch = parseNumParam(params.pitch, obj, 0);
    const rel = params.relative === true || params.relative === 'true' ||
                params.relative === 1 || params.relative === '1';
    if (rel) pitch += (cfg.pitch || 0);
    cfg.pitch = bwClampPitch(pitch);
});

registerExtensionAction('select_hotbar_slot', function(obj, params, game) {
    let index = Math.trunc(parseNumParam(params.index, obj, 0));
    const rel = params.relative === true || params.relative === 'true' ||
                params.relative === 1 || params.relative === '1';
    if (rel) index += Math.trunc(obj.hotbar_index || 0);
    const n = BW_DEFAULT_HOTBAR.length;
    index = ((index % n) + n) % n;
    obj.hotbar_index = index;
    obj.hotbar_block = BW_DEFAULT_HOTBAR[index];
});

registerExtensionAction('move_and_collide', function(obj, params, game) {
    if (!game || !game.currentRoom) return;
    const room = game.currentRoom;
    const cfg = room.blockWorldCamera;
    if (!cfg || !cfg.enabled) return;

    const dx = parseNumParam(params.dx, obj, 0);
    const dy = parseNumParam(params.dy, obj, 0);
    const collide = !(params.collide === false || params.collide === 'false' ||
                       params.collide === 0 || params.collide === '0');
    const cellSize = cfg.cell_size || 32;

    const tl = GameRoom.spriteTopLeft(obj);
    let tlX = tl.x, tlY = tl.y;
    let standing = bwGroundLayer(room, bwCellOf(tlX, cellSize), bwCellOf(tlY, cellSize));

    const nx = tlX + dx;
    if (!collide || bwCanEnter(room, bwCellOf(nx, cellSize), bwCellOf(tlY, cellSize), standing)) {
        obj.x += dx; tlX = nx;
    }
    const ny = tlY + dy;
    if (!collide || bwCanEnter(room, bwCellOf(tlX, cellSize), bwCellOf(ny, cellSize), standing)) {
        obj.y += dy; tlY = ny;
    }

    standing = bwGroundLayer(room, bwCellOf(tlX, cellSize), bwCellOf(tlY, cellSize));
    const camera = room.findFirstInstance(cfg.camera_object || '');
    if (camera === obj) cfg.z_layer = standing;
});

registerExtensionAction('place_block', function(obj, params, game) {
    const picked = bwPick(obj, params, game);
    if (!picked || !picked.placement) return;
    let block = params.block !== undefined ? String(params.block) : 'stone';
    if (!BLOCK_FACE_COLORS.hasOwnProperty(block)) {
        // Not a literal block-type id -- try it as an instance-variable
        // reference (e.g. "hotbar_block", select_hotbar_slot's own
        // convention -- mirrors handlers.execute_place_block_action's
        // ae._parse_value resolving a bare instance attribute name).
        const resolved = gmExpressionValue(params.block, obj, game);
        if (resolved !== undefined && resolved !== null) block = String(resolved);
    }
    if (!BLOCK_FACE_COLORS.hasOwnProperty(block)) return;
    bwSetBlock(picked.room, picked.placement[0], picked.placement[1], picked.placement[2], block);
});

registerExtensionAction('break_block', function(obj, params, game) {
    const picked = bwPick(obj, params, game);
    if (!picked || !picked.target) return;
    const bt = bwGetBlock(picked.room, picked.target[0], picked.target[1], picked.target[2]);
    if (bt !== null && BW_UNBREAKABLE.has(bt)) return;
    bwRemoveBlock(picked.room, picked.target[0], picked.target[1], picked.target[2]);
});

registerExtensionAction('enable_block_world_view', function(obj, params, game) {
    if (!game || !game.currentRoom) return;
    const enable = !(params.enable === false || params.enable === 'false' ||
                      params.enable === 0 || params.enable === '0');
    const room = game.currentRoom;
    if (!enable) { room.blockWorldCamera = { enabled: false }; return; }

    const num = (k, d) => {
        const n = parseNumParam(params[k], obj, d);
        return (typeof n === 'number' && isFinite(n)) ? n : d;
    };
    room.blockWorldCamera = {
        enabled: true,
        camera_object: params.camera_object || obj.name,
        z_layer: Math.trunc(num('z_layer', 0)),
        fov: num('fov', 66),
        render_distance: Math.trunc(num('render_distance', 20)),
        cell_size: Math.trunc(num('cell_size', 32)),
        columns: Math.trunc(num('columns', 320)),
        wall_color: params.wall_color || '#8a8a8a',
        floor_color: params.floor_color || '#3a2f1c',
        ceiling_color: params.ceiling_color || '#87CEEB',
        wall_textured: !(params.wall_textured === false || params.wall_textured === 'false'),
        pitch: bwClampPitch(num('pitch', 0)),
        eye_height: num('eye_height', BW_DEFAULT_EYE_HEIGHT),
    };
    room._bwColumns = null;
});

registerExtensionAction('load_block_world', function(obj, params, game) {
    if (!game || !game.currentRoom) return;
    const dataFile = String(params.data_file || '');
    if (!dataFile) return;

    const extData = (game.gameData && game.gameData._extension_data) || {};
    const files = extData.block_world_files || {};
    const blockList = files[dataFile];
    if (!Array.isArray(blockList)) return;   // missing/unbundled file -- no-op

    // Atomic: an unknown block type rejects the WHOLE file, mirroring
    // state.load_block_list's KeyError (which the desktop action's own
    // no-op-on-bad-input handling then swallows).
    const blocks = {};
    for (const entry of blockList) {
        const bt = entry && entry.type;
        if (!BLOCK_FACE_COLORS.hasOwnProperty(bt)) return;
        blocks[entry.x + ',' + entry.y + ',' + entry.z] = bt;
    }
    game.currentRoom._bwBlocks = blocks;
    game.currentRoom._bwColumns = null;
});

registerExtensionAction('draw_block_world_hud', function(obj, params, game) {
    if (!obj._draw_queue) obj._draw_queue = [];
    const screenW = (game && game.canvas && game.canvas.width) || 640;
    const screenH = (game && game.canvas && game.canvas.height) || 480;
    const num = (k, d) => {
        const n = parseNumParam(params[k], obj, d);
        return (typeof n === 'number' && isFinite(n)) ? n : d;
    };
    const cmds = bwBuildHudCommands(
        screenW, screenH, BW_DEFAULT_HOTBAR, Math.trunc(obj.hotbar_index || 0),
        num('slot_size', 40), num('gap', 6), num('margin_bottom', 16),
        params.back_color || '#202020', params.border_color || '#ffffff',
        params.selected_color || '#ffd040', params.text_color || '#ffffff',
        num('crosshair_size', 12), params.crosshair_color || '#ffffff');
    obj._draw_queue.push(...cmds);
});
